# vim: filetype=yaml
steps:
  - name: ":chopsticks: Test"
    command: "go get github.com/chakrit/smoke@v0.2.3 && ./smoke -vv"
    key: test
  - name: ":wrench: Build"
    command: "docker build -t masqer-$BUILDKITE_COMMIT ."
    key: build
    depends_on: test
  - name: ":paperclip: Tag"
    command: "docker tag masqer-$BUILDKITE_COMMIT ghcr.io/prod9/masqer"
    key: tag
    depends_on: build
  - name: ":rocket: Publish"
    command: "docker push ghcr.io/prod9/masqer"
    depends_on: tag
